# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .data_object import DataObject
from .dpa_data import DpaData
from .dpa_transaction_options import DpaTransactionOptions


class Amex(DataObject):

    __dpa_data: Optional[DpaData] = None
    __dpa_transaction_options: Optional[DpaTransactionOptions] = None
    __src_initiator_id: Optional[str] = None

    @property
    def dpa_data(self) -> Optional[DpaData]:
        """
        | DpaData data should be provided to SRC system if srcDpaId is not provided.

        Type: :class:`onlinepayments.sdk.domain.dpa_data.DpaData`
        """
        return self.__dpa_data

    @dpa_data.setter
    def dpa_data(self, value: Optional[DpaData]) -> None:
        self.__dpa_data = value

    @property
    def dpa_transaction_options(self) -> Optional[DpaTransactionOptions]:
        """
        | DPA configuration data that can override any configuration set before.

        Type: :class:`onlinepayments.sdk.domain.dpa_transaction_options.DpaTransactionOptions`
        """
        return self.__dpa_transaction_options

    @dpa_transaction_options.setter
    def dpa_transaction_options(self, value: Optional[DpaTransactionOptions]) -> None:
        self.__dpa_transaction_options = value

    @property
    def src_initiator_id(self) -> Optional[str]:
        """
        | SRCI identifier. This is generated by the SRC System during onboarding.

        Type: str
        """
        return self.__src_initiator_id

    @src_initiator_id.setter
    def src_initiator_id(self, value: Optional[str]) -> None:
        self.__src_initiator_id = value

    def to_dictionary(self) -> dict:
        dictionary = super(Amex, self).to_dictionary()
        if self.dpa_data is not None:
            dictionary['dpaData'] = self.dpa_data.to_dictionary()
        if self.dpa_transaction_options is not None:
            dictionary['dpaTransactionOptions'] = self.dpa_transaction_options.to_dictionary()
        if self.src_initiator_id is not None:
            dictionary['srcInitiatorId'] = self.src_initiator_id
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'Amex':
        super(Amex, self).from_dictionary(dictionary)
        if 'dpaData' in dictionary:
            if not isinstance(dictionary['dpaData'], dict):
                raise TypeError('value \'{}\' is not a dictionary'.format(dictionary['dpaData']))
            value = DpaData()
            self.dpa_data = value.from_dictionary(dictionary['dpaData'])
        if 'dpaTransactionOptions' in dictionary:
            if not isinstance(dictionary['dpaTransactionOptions'], dict):
                raise TypeError('value \'{}\' is not a dictionary'.format(dictionary['dpaTransactionOptions']))
            value = DpaTransactionOptions()
            self.dpa_transaction_options = value.from_dictionary(dictionary['dpaTransactionOptions'])
        if 'srcInitiatorId' in dictionary:
            self.src_initiator_id = dictionary['srcInitiatorId']
        return self
