# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .authentication_options import AuthenticationOptions
from .data_object import DataObject


class Mastercard(DataObject):

    __authentication_options: Optional[AuthenticationOptions] = None
    __src_initiator_id: Optional[str] = None
    __srci_dpa_id: Optional[str] = None

    @property
    def authentication_options(self) -> Optional[AuthenticationOptions]:
        """
        | Authentication options to execute passkeys or 3DS authentication for transactions.

        Type: :class:`onlinepayments.sdk.domain.authentication_options.AuthenticationOptions`
        """
        return self.__authentication_options

    @authentication_options.setter
    def authentication_options(self, value: Optional[AuthenticationOptions]) -> None:
        self.__authentication_options = value

    @property
    def src_initiator_id(self) -> Optional[str]:
        """
        | Identifier for the integrator. This is generated by the Mastercard System during onboarding.

        Type: str
        """
        return self.__src_initiator_id

    @src_initiator_id.setter
    def src_initiator_id(self, value: Optional[str]) -> None:
        self.__src_initiator_id = value

    @property
    def srci_dpa_id(self) -> Optional[str]:
        """
        | DPA Identifier. This is generated by the integrator during registration.

        Type: str
        """
        return self.__srci_dpa_id

    @srci_dpa_id.setter
    def srci_dpa_id(self, value: Optional[str]) -> None:
        self.__srci_dpa_id = value

    def to_dictionary(self) -> dict:
        dictionary = super(Mastercard, self).to_dictionary()
        if self.authentication_options is not None:
            dictionary['authenticationOptions'] = self.authentication_options.to_dictionary()
        if self.src_initiator_id is not None:
            dictionary['srcInitiatorId'] = self.src_initiator_id
        if self.srci_dpa_id is not None:
            dictionary['srciDpaId'] = self.srci_dpa_id
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'Mastercard':
        super(Mastercard, self).from_dictionary(dictionary)
        if 'authenticationOptions' in dictionary:
            if not isinstance(dictionary['authenticationOptions'], dict):
                raise TypeError('value \'{}\' is not a dictionary'.format(dictionary['authenticationOptions']))
            value = AuthenticationOptions()
            self.authentication_options = value.from_dictionary(dictionary['authenticationOptions'])
        if 'srcInitiatorId' in dictionary:
            self.src_initiator_id = dictionary['srcInitiatorId']
        if 'srciDpaId' in dictionary:
            self.srci_dpa_id = dictionary['srciDpaId']
        return self
