# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .data_object import DataObject


class PaymentProduct5002defaultBrandParameters(DataObject):

    __src_dpa_id: Optional[str] = None
    __src_initiator_id: Optional[str] = None

    @property
    def src_dpa_id(self) -> Optional[str]:
        """
        | The reference identifier that has been generated either by the SRC Initiator or by the SRC System. During DPA Registration with the SRC System, this value will identify the DPA for subsequent initialisations.

        Type: str
        """
        return self.__src_dpa_id

    @src_dpa_id.setter
    def src_dpa_id(self, value: Optional[str]) -> None:
        self.__src_dpa_id = value

    @property
    def src_initiator_id(self) -> Optional[str]:
        """
        | The reference identifier generated by the SRC System during Onboarding of the SRC Initiator to the SRC System.

        Type: str
        """
        return self.__src_initiator_id

    @src_initiator_id.setter
    def src_initiator_id(self, value: Optional[str]) -> None:
        self.__src_initiator_id = value

    def to_dictionary(self) -> dict:
        dictionary = super(PaymentProduct5002defaultBrandParameters, self).to_dictionary()
        if self.src_dpa_id is not None:
            dictionary['srcDpaId'] = self.src_dpa_id
        if self.src_initiator_id is not None:
            dictionary['srcInitiatorId'] = self.src_initiator_id
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'PaymentProduct5002defaultBrandParameters':
        super(PaymentProduct5002defaultBrandParameters, self).from_dictionary(dictionary)
        if 'srcDpaId' in dictionary:
            self.src_dpa_id = dictionary['srcDpaId']
        if 'srcInitiatorId' in dictionary:
            self.src_initiator_id = dictionary['srcInitiatorId']
        return self
