# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .data_object import DataObject


class RedirectPaymentProduct3204SpecificInput(DataObject):

    __blik_code: Optional[str] = None

    @property
    def blik_code(self) -> Optional[str]:
        """
        | Code required for BLIK payments generated by the buyer's bank application

        Type: str
        """
        return self.__blik_code

    @blik_code.setter
    def blik_code(self, value: Optional[str]) -> None:
        self.__blik_code = value

    def to_dictionary(self) -> dict:
        dictionary = super(RedirectPaymentProduct3204SpecificInput, self).to_dictionary()
        if self.blik_code is not None:
            dictionary['blikCode'] = self.blik_code
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'RedirectPaymentProduct3204SpecificInput':
        super(RedirectPaymentProduct3204SpecificInput, self).from_dictionary(dictionary)
        if 'blikCode' in dictionary:
            self.blik_code = dictionary['blikCode']
        return self
