# -*- coding: utf-8 -*-
#
# This file was automatically generated.
#
from typing import Optional

from .data_object import DataObject
from .visa_authentication_options import VisaAuthenticationOptions


class Visa(DataObject):

    __authentication_options: Optional[VisaAuthenticationOptions] = None
    __encryption_key: Optional[str] = None
    __n_modulus: Optional[str] = None
    __src_initiator_id: Optional[str] = None
    __srci_dpa_id: Optional[str] = None

    @property
    def authentication_options(self) -> Optional[VisaAuthenticationOptions]:
        """
        | 3-D Secure options to execute 3DS authentication for transaction.

        Type: :class:`onlinepayments.sdk.domain.visa_authentication_options.VisaAuthenticationOptions`
        """
        return self.__authentication_options

    @authentication_options.setter
    def authentication_options(self, value: Optional[VisaAuthenticationOptions]) -> None:
        self.__authentication_options = value

    @property
    def encryption_key(self) -> Optional[str]:
        """
        | KID (Key ID) of the encryption key to encrypt card information before sending it to Visa.

        Type: str
        """
        return self.__encryption_key

    @encryption_key.setter
    def encryption_key(self, value: Optional[str]) -> None:
        self.__encryption_key = value

    @property
    def n_modulus(self) -> Optional[str]:
        """
        | Modulus of the encryption key to encrypt card information before sending it to Visa.

        Type: str
        """
        return self.__n_modulus

    @n_modulus.setter
    def n_modulus(self, value: Optional[str]) -> None:
        self.__n_modulus = value

    @property
    def src_initiator_id(self) -> Optional[str]:
        """
        | SRCI identifier generated by an SRC system during the onboarding process.

        Type: str
        """
        return self.__src_initiator_id

    @src_initiator_id.setter
    def src_initiator_id(self, value: Optional[str]) -> None:
        self.__src_initiator_id = value

    @property
    def srci_dpa_id(self) -> Optional[str]:
        """
        | A unique ID provided by the SRCI for the DPA, which can be used as an external client ID. Required if srciDpaId in dpaData is not provided.

        Type: str
        """
        return self.__srci_dpa_id

    @srci_dpa_id.setter
    def srci_dpa_id(self, value: Optional[str]) -> None:
        self.__srci_dpa_id = value

    def to_dictionary(self) -> dict:
        dictionary = super(Visa, self).to_dictionary()
        if self.authentication_options is not None:
            dictionary['authenticationOptions'] = self.authentication_options.to_dictionary()
        if self.encryption_key is not None:
            dictionary['encryptionKey'] = self.encryption_key
        if self.n_modulus is not None:
            dictionary['nModulus'] = self.n_modulus
        if self.src_initiator_id is not None:
            dictionary['srcInitiatorId'] = self.src_initiator_id
        if self.srci_dpa_id is not None:
            dictionary['srciDpaId'] = self.srci_dpa_id
        return dictionary

    def from_dictionary(self, dictionary: dict) -> 'Visa':
        super(Visa, self).from_dictionary(dictionary)
        if 'authenticationOptions' in dictionary:
            if not isinstance(dictionary['authenticationOptions'], dict):
                raise TypeError('value \'{}\' is not a dictionary'.format(dictionary['authenticationOptions']))
            value = VisaAuthenticationOptions()
            self.authentication_options = value.from_dictionary(dictionary['authenticationOptions'])
        if 'encryptionKey' in dictionary:
            self.encryption_key = dictionary['encryptionKey']
        if 'nModulus' in dictionary:
            self.n_modulus = dictionary['nModulus']
        if 'srcInitiatorId' in dictionary:
            self.src_initiator_id = dictionary['srcInitiatorId']
        if 'srciDpaId' in dictionary:
            self.srci_dpa_id = dictionary['srciDpaId']
        return self
